### ISSUE TITLE
vague warning about clipping

### ISSUE THREAD

**Issue by denalena** [sergree/matchering-cli#1]
I got the following warning:
`WARNING: Audio clipping is detected in the TARGET file. It is highly recommended to use the non-clipping version`

What does this exactly recommend? Using the --no_limiter switch?
**update**: just tried with --no_limiter and also with --dont_normalize, the warning does not disappear. Wouldn't it be rather easy to avoid clipping during the whole process?

Thanks so much btw for this project, it's amazing!

**Comment by sergree** [comment]
Hello, @ledeniz !
Thank you for your feedback!

This warning means that your TARGET track (first audio file) has >8 samples with 1. value.
This usually means that your input file is clipping. To fix this, you need to export your mix in 32-bit WAV format (in your DAW). Or reduce the volume of the master channel by a few decibels so that the peaks disappear.

**Comment by denalena** [comment]
I see, that makes perfectly sense :) Thank you for your help.
